Fixed some things.
seasonguy/CommunityMinecraftPlugin pull request #2
Opened 2017-10-03 22:05 UTC by Kameramann23

Fixed: 
* Core.java
* HelloWorldChatListener.java 
* HelloWorldCommand.java

2017-10-03 22:06 UTC, Kameramann23 commented
* pom.xml
-> Missing bukkit dependency
-> Missing spigot repository

2017-10-04 01:16 UTC, seasonguy requested changes

2017-10-04 01:16 UTC, seasonguy commented on src/main/java/io/github/communityminecraftplugin/communityminecraftplugin/HelloWorldCommand.java
> +		if(c.getName().equalsIgnoreCase("helloworld")) {
This is an extraneous check and should be removed. The class is a single commandexecutor assigned to the helloworld command already in the onEnable

2017-10-04 12:13 UTC, Kameramann23 commented
I changed it.

2017-10-04 17:07 UTC, seasonguy approved these changes

2017-10-04 17:07 UTC, merged